projeto25/projeto25/projeto25/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rmbebidas.urls')),
]

projeto25/projeto25/rmbebidas/urls.py
from django.urls import path
from . import views

app_name="rmbebidas"

urlpatterns=[
	path('',views.viewindex,name="index"),
	path('index/',views.viewindex,name="index"),
	path('tpainel/',views.viewtpainel,name="tpainel"),
	path('tproduto/',views.viewtproduto,name="tproduto"),
	path('tverproduto/',views.viewtverproduto,name="tverproduto"),
	path('tcadusuarios/',views.viewtcadusuarios,name="tcadusuarios"),
	path('tusuarios/',views.viewtusuarios,name="tusuarios"),
	path('teditusuario/<int:id>',views.viewteditusuario,name="teditusuario"),
	path('tprecos/',views.viewtprecos,name="tprecos"),
	

	# btns
	path('defbtnlogin/',views.defbtnlogin,name="defbtnlogin"),
	path('defbtnnvproduto/',views.defbtnnvproduto,name="defbtnnvproduto"),
	path('defbtnverproduto/<int:id>',views.defbtnverproduto,name="defbtnverproduto"),
	path('defbtneditproduto/<int:id>',views.defbtneditproduto,name="defbtneditproduto"),
	path('defbtndellproduto/<int:id>',views.defbtndellproduto,name="defbtndellproduto"),
	path('defbtndellproduto/<int:id>',views.defbtndellproduto,name="defbtndellproduto"),
	path('defbtncadusuarios/',views.defbtncadusuarios,name="defbtncadusuarios"),
	path('defbtndellusuario/<int:id>',views.defbtndellusuario,name="defbtndellusuario"),
	path('defbtneditusuario/<int:id>',views.defbtneditusuario,name="defbtneditusuario"),
]

projeto25/projeto25/rmbebidas/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class TbProdutos(models.Model):
    pro_codigo = models.AutoField(primary_key=True)
    pro_nome = models.CharField(max_length=45, blank=True, null=True)
    pro_quantidade = models.IntegerField(blank=True, null=True)
    pro_descricao = models.TextField(blank=True, null=True)
    pro_fornecedor = models.CharField(max_length=45, blank=True, null=True)
    pro_preco = models.FloatField(blank=True, null=True)
    pro_marca = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'tb_produtos'


class TbUsuarios(models.Model):
    usu_codigo = models.AutoField(primary_key=True)
    usu_nome = models.CharField(max_length=50, blank=True, null=True)
    usu_sobrenome = models.CharField(max_length=50, blank=True, null=True)
    usu_email = models.CharField(max_length=120, blank=True, null=True)
    usu_senha = models.CharField(max_length=120, blank=True, null=True)
    usu_admin = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'tb_usuarios'

projeto25/projeto25/rmbebidas/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404 as error404
from . import urls
from django.http import HttpResponse
from .models import TbProdutos, TbUsuarios

#######################################################
# Usuario padrão/inicial:
# email: user@user senha: root
#######################################################

def viewindex(request):
	return render(request,'index.html')

def viewtcadusuarios(request):
	return render(request,'tcadusuarios.html')

def viewtproduto(request):
	return render(request,'tproduto.html')

def viewtprecos(request):
	produtos=TbProdutos.objects.all()
	return render(request,'tprecos.html',{'PRODUTO':produtos})

def viewtverproduto(request):
	return render(request,'tverproduto.html')

def viewtusuarios(request):
	funcionario=TbUsuarios.objects.all()
	return render(request,'tusuarios.html',{'FUNCIONARIO':funcionario})

def viewteditusuario(request,id):
	funcionario=TbUsuarios.objects.get(usu_codigo=id)
	return render(request,'teditusuario.html',{'FUNCIONARIO':funcionario})

def viewtpainel(request):
	produtos=TbProdutos.objects.all()
	if produtos:
		return render(request,'tpainel.html',{'PRODUTO':produtos})
	else:
		return render(request,'tpainel.html',{'PRODUTO':produtos,'vazioAlert':"Estante vazia"})

def defbtnlogin(request):
	if request.method=="POST":
		email=request.POST.get('email')
		senha=request.POST.get('senha')
		
		# procurando se esse email já existe no banco
		try:
			busca=error404(TbUsuarios,usu_email=email)
			#aqui ele verifica se a variável está vazia ou  não, se estiver é pq o email inserido não exise no banco, se não estiver é pq vc existe no banco
			if busca:
				# se ele encontrar o email, ele vai verificar se a senha esta certa
				if senha == busca.usu_senha:
					return redirect('rmbebidas:tpainel')
				else:
					return render(request,'index.html',{'senhaAlert1':"Senha Errada",'keepEmail':email,'keepSenha':senha})
		
		except:
			return render(request,'index.html',{'emailAlert1':"Email não encontrado",'keepEmail':email,'keepSenha':senha})
	else:
		return render(request,'index.html',{'getERROR':"Acesso GET negado"})


def defbtnnvproduto(request):
	if request.method=="POST":
		nome = request.POST.get('nome')
		quantidade = request.POST.get('quantidade')
		descricao = request.POST.get('descricao')
		fornecedor = request.POST.get('fornecedor')
		preco = request.POST.get('preco')
		marca = request.POST.get('marca')

		produto=TbProdutos(pro_nome=nome,pro_quantidade=quantidade,pro_descricao=descricao,pro_fornecedor=fornecedor,pro_preco=preco,pro_marca=marca)
		produto.save()
		produtos=TbProdutos.objects.all()
		return render(request,'tproduto.html')
	else:
		return render(request,'tproduto.html',{'getERROR2':"Acesso GET negado"})


def defbtnverproduto(request,id):
	produto=TbProdutos.objects.get(pro_codigo=id) #pegando o produto através da sua chave
	produtos=TbProdutos.objects.all()
	return render(request,'tverproduto.html',{'PRODUTO':produto})

def defbtneditproduto(request,id):
	if request.method=="POST":
		produto=TbProdutos.objects.get(pro_codigo=id) #pegando o produto através da sua chave
		produto.pro_nome = request.POST.get('nome')
		produto.pro_quantidade = request.POST.get('quantidade')
		produto.pro_descricao = request.POST.get('descricao')
		produto.pro_fornecedor = request.POST.get('fornecedor')
		produto.pro_preco = request.POST.get('preco')
		produto.pro_marca = request.POST.get('marca')
		produto.save()
		
		produtos=TbProdutos.objects.all()
		return render(request,'tpainel.html',{'PRODUTO':produtos})


def defbtndellproduto(request,id):
	try:
		produto=TbProdutos.objects.get(pro_codigo=id) #pegando o produto através da sua chave
		produto.delete()
		
		produtos=TbProdutos.objects.all()
		return render(request,'tpainel.html',{'PRODUTO':produtos})
	except:
		produtos=TbProdutos.objects.all()
		return render(request,'tpainel.html',{'PRODUTO':produtos})


def defbtncadusuarios (request):
	if request.method=="POST":
		senha=request.POST.get('senha')
		nome=request.POST.get('nome')
		sobrenome=request.POST.get('sobrenome')
		
		email=request.POST.get('email')
		busca=TbUsuarios.objects.filter(usu_email=email)
		
		if busca:
			return render(request,'tcadusuarios.html',{'emailExiste':"Email já cadastrado",'keepEmail':email,'keepSenha':senha,'keepNome':nome,'keepSobrenome':sobrenome})
		else:
			usuario=TbUsuarios(usu_nome=nome,usu_sobrenome=sobrenome,usu_email=email,usu_senha=senha)
			usuario.save()			
			return render(request,'tcadusuarios.html',{'cadSucesso':"Usuario Cadastrado",'keepEmail':email,'keepSenha':senha,'keepNome':nome,'keepSobrenome':sobrenome})
	else:
		return render(request,'tproduto.html',{'getERROR3':"Acesso GET negado"})


def defbtndellusuario(request,id):
	try:
		dellfuncionario=TbUsuarios.objects.get(usu_codigo=id)
		dellfuncionario.delete()

		funcionario=TbUsuarios.objects.all()
		return render(request,'tusuarios.html',{'FUNCIONARIO':funcionario})
	except:
		funcionario=TbUsuarios.objects.all()
		return render(request,'tusuarios.html',{'FUNCIONARIO':funcionario})


def defbtneditusuario(request,id):
	if request.method=="POST":
		editfuncionario=TbUsuarios.objects.get(usu_codigo=id)
		editfuncionario.usu_nome = request.POST.get('nome')
		editfuncionario.usu_sobrenome = request.POST.get('sobrenome')
		editfuncionario.usu_email = request.POST.get('email')
		editfuncionario.usu_senha = request.POST.get('senha')
		editfuncionario.save()
		funcionario=TbUsuarios.objects.all()
		return render(request,'tusuarios.html',{'FUNCIONARIO':funcionario})
	else:		
		funcionario=TbUsuarios.objects.get(usu_codigo=id)
		return render(request,'teditusuario.html',{'FUNCIONARIO':funcionario,'getERROR4':"Acesso GET negado"})

projeto25/projeto25/rmbebidas/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>RMBEBIDAS</title>
</head>
<body>

{% block nav %} 
<!-- esta sendo puxado -->
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <nav>
        <ol class="breadcrumb"> 
          <li class="breadcrumb-item">
            <a href="{% url 'rmbebidas:tpainel' %}">Estante</a>    
          </li>
          <li class="breadcrumb-item">
            <a href="{% url 'rmbebidas:tprecos' %}">Tabela</a>    
          </li>
          <li class="breadcrumb-item">
            <a href="{% url 'rmbebidas:tproduto' %}">Adicionar Produto</a>    
          </li>
          <li class="breadcrumb-item">
            <a href="{% url 'rmbebidas:tcadusuarios' %}">Novo Funcionário</a>
          </li>
          <li class="breadcrumb-item">
            <a href="{% url 'rmbebidas:tusuarios' %}">Funcionários</a>
          </li>
          <li class="breadcrumb-item">
            <a href="{% url 'rmbebidas:index' %}">Sair</a>    
          </li>
        </ol>
      </nav>
    </div>
  </div>
</div>
{% endblock nav %}

{% block conteudo %}
<!-- qualquer coisa pode ser colocado aqui dentro -->
<!-- espaço para o conteudo - sobreescrita-->
{% endblock conteudo %}


</body>
</html>

projeto25/projeto25/rmbebidas/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<title>RMBEBIDAS</title>

  <script type="text/javascript">
    function versenha(){

      var tag = document.getElementById("inputSenha");

      if (tag.type=="password") {
        tag.type="text";
      } else{
        tag.type="password";
      }

  </script>

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'rmbebidas:index' %}">RMBEBIDAS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
    </ul>
    <span class="navbar-text">
      RMBEBIDAS
    </span>
  </div>
</nav>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
      <form role="form" method="POST" action="{% url 'rmbebidas:defbtnlogin' %}">
         {% csrf_token %}
        <div class="form-group">
          <label for="exampleInputEmail1">
            Email
          </label>
          <input type="email" class="form-control" id="exampleInputEmail1" name="email" value="{{keepEmail}}" />
        {{emailAlert1}}
        </div>
        <div class="form-group">
           
          <label for="exampleInputPassword1">
            Senha
          </label>
          
          <input type="password" class="form-control" id="inputSenha" name="senha" value="{{keepSenha}}"/>
          {{senhaAlert1}}
<!-- 
        <div class="checkbox">
          <input type="checkbox" onclick="versenha()" /> 
          <label>Ver Senha</label>
        </div>
 -->

        </div>
        <button type="submit" class="btn btn-primary">
          Entrar
        </button>
      </form>
    </div>
    <div class="col-md-4">
    </div>
  </div>
</div>

<div class="container-fluid" style="display: flex; justify-content: center; align-items: center;">
  {{getERROR}}
</div>

</body>
</html> 

projeto25/projeto25/rmbebidas/templates/tcadusuarios.html
{% extends "base.html" %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>RMBEBIDAS</title>
</head>
<body>
{% block nav %}
{{block.super}}
{% endblock nav %}

{% block conteudo %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-4">
		</div>

		<div class="col-md-4">
			<form method="POST" action="{% url 'rmbebidas:defbtncadusuarios' %}">
			  {% csrf_token %}
			  <div class="form-row">
			    <div class="form-group col-md-6">
			      <label for="inputEmail4">Nome</label>
			      <input type="text" class="form-control" id="inputEmail4" placeholder="Nome" required name="nome" value="{{keepNome}}">
			    </div>
			    <div class="form-group col-md-6">
			      <label for="inputPassword4">Sobrenome</label>
			      <input type="text" class="form-control" id="inputPassword4" required placeholder="Sobrenome" name="sobrenome" value="{{keepSobrenome}}">
			    </div>
			  </div>
			  <div class="form-row">
			    <div class="form-group col-md-6">
			      <label for="inputPassword4">Email</label>
			      <input type="text" class="form-control" id="inputPassword4" required placeholder="Email" name="email" value="{{keepEmail}}">
			    </div>
			    <div class="form-group col-md-6">
			      <label for="inputPassword4">Senha</label>
			      <input type="password" class="form-control" id="inputPassword4" required placeholder="Senha" name="senha" value="{{keepSenha}}">
			    </div>
			  </div>
			  <input type="submit" value="Cadastrar" class="btn btn-primary">
			</form>
		</div>

		<div class="col-md-4">
		</div>
	</div>
</div>

<div class="container-fluid" style="display: flex; align-items: center; justify-content: center;">
	{{getERROR3}}
	{{emailExiste}}
	{{cadSucesso}}
</div>
{% endblock conteudo %}

</body>
</html>

projeto25/projeto25/rmbebidas/templates/teditusuario.html
{% extends "base.html" %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>RMBEBIDAS</title>
</head>
<body>
{% block nav %}
{{block.super}}
{% endblock nav %}

{% block conteudo %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-4">
		</div>

		<div class="col-md-4">
			<form method="POST" action="{% url 'rmbebidas:defbtneditusuario' FUNCIONARIO.usu_codigo %}">
			  {% csrf_token %}
			  <div class="form-row">
			    <div class="form-group col-md-6">
			      <label for="inputEmail4">Nome</label>
			      <input type="text" class="form-control" id="inputEmail4" placeholder="Nome" required name="nome" value="{{FUNCIONARIO.usu_nome}}">
			    </div>
			    <div class="form-group col-md-6">
			      <label for="inputPassword4">Sobrenome</label>
			      <input type="text" class="form-control" id="inputPassword4" required placeholder="Sobrenome" name="sobrenome" value="{{FUNCIONARIO.usu_sobrenome}}">
			    </div>
			  </div>
			  <div class="form-row">
			    <div class="form-group col-md-6">
			      <label for="inputPassword4">Email</label>
			      <input type="text" class="form-control" id="inputPassword4" required placeholder="Email" name="email" value="{{FUNCIONARIO.usu_email}}">
			    </div>
			    <div class="form-group col-md-6">
			      <label for="inputPassword4">Senha</label>
			      <input type="text" class="form-control" id="inputPassword4" required placeholder="Senha" name="senha" value="{{FUNCIONARIO.usu_senha}}">
			    </div>
			  </div>
			  <input type="submit" value="Salvar" class="btn btn-primary">
			</form>
		</div>

		<div class="col-md-4">
		</div>
	</div>
</div>

<div class="container-fluid" style="display: flex; align-items: center; justify-content: center;">
	{{getERROR4}}
</div>
{% endblock conteudo %}

</body>
</html>

projeto25/projeto25/rmbebidas/templates/tpainel.html
{% extends "base.html" %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>RMBEBIDAS</title>
</head>
<body>

{% block nav %}
{{ block.super }}
{% endblock nav %}

{% block conteudo %}
<div class="container-fluid" style="display: flex; justify-content: center; align-items: center;">
	{{vazioAlert}}
	{{existProdutoAlert}}
</div>

<div class="container-fluid">

	<div class="card-columns">

{% for produtos in PRODUTO %}
	<div class="card border-dark mb-3">
	  	<div class="card-body text-dark">
		    <h5 class="card-title">{{produtos.pro_nome}}</h5>
		    <p class="card-text">{{produtos.pro_descricao}}</p>
		    <div class="card-footer">
		      <small class="text-muted">Marca: {{produtos.pro_marca}}</small>
		    <hr>
		      <small class="text-muted">Fornecedor: {{produtos.pro_fornecedor}}</small>
		    <hr>
		      <small class="text-muted">Estoque: {{produtos.pro_quantidade}}</small>
		    <hr>
		      <small class="text-muted">Preço: R${{produtos.pro_preco}}</small>
		    </div>
		    	
		    <a href="{% url 'rmbebidas:defbtnverproduto' produtos.pro_codigo %}">
				<button type="button" class="btn btn-outline-dark">Abrir</button>
			</a>
	  	</div>
  	</div>

{% endfor %}
	</div>

</div>

{% endblock conteudo %}

</body>
</html>

projeto25/projeto25/rmbebidas/templates/tusuarios.html
{% extends "base.html" %}
<<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>RMBEBIDAS</title>

</head>
<body>
{% block nav %}
{{block.super}}
{% endblock nav %}

{% block conteudo %}

<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<table class="table table-striped">
				<thead>
					<tr>
						<th>
							Nome do Funcionário
						</th>
						<th>
							Sobrenome do Funcionário
						</th>
						<th>
							Email do Funcionário
						</th>
					</tr>
				</thead>
				<tbody>
					

					{% for funcionario in FUNCIONARIO %}
					<tr class="table-success">
						<td>
							{{funcionario.usu_nome}}
						</td>
						<td>
							{{funcionario.usu_sobrenome}}
						</td>
						<td>
							{{funcionario.usu_email}}
						</td>
						<td>
							<a href=" {% url 'rmbebidas:teditusuario' funcionario.usu_codigo %} ">
								<button class="btn btn-primary">
									Editar
								</button>
							</a>
							<a href="{% url 'rmbebidas:defbtndellusuario' funcionario.usu_codigo %}">
								<button class="btn btn-danger">
									Desativar
								</button>
							</a>
						</td>
					</tr>
					{% endfor %}


				</tbody>
			</table>
		</div>
	</div>
</div>
{{DeletErrorAlert}}
{{DeletSucessesAlert}}
{% endblock conteudo %}

</body>
</html>



projeto25/projeto25/rmbebidas/templates/tverproduto.html
{% extends "base.html" %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>RMBEBIDAS</title>
</head>
<body>
{% block nav %}
{{block.super}}
{% endblock nav %}

{% block conteudo %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-4">
		</div>

		<div class="col-md-4">
			<form method="POST" action="{% url 'rmbebidas:defbtneditproduto' PRODUTO.pro_codigo %}">
			  {% csrf_token %}
			  <div class="form-row">
			    <div class="form-group col-md-6">
			      <label for="inputEmail4">Marca</label>
			      <input type="text" class="form-control" id="inputEmail4" placeholder="Marca do Produto" required name="marca" value="{{PRODUTO.pro_marca}}" >
			    </div>
			    <div class="form-group col-md-6">
			      <label for="inputPassword4">Nome</label>
			      <input type="text" class="form-control" id="inputPassword4" required placeholder="Nome do Produto" name="nome" value="{{PRODUTO.pro_nome}}">
			    </div>
			  </div>
			  <div class="form-row">
			    <div class="form-group col-md-6">
			      <label for="inputCity">Quantidade</label>
			      <input type="number" class="form-control" id="inputCity" required placeholder="Estoque" name="quantidade" value="{{PRODUTO.pro_quantidade}}">
			    </div>
			    <div class="form-group col-md-4">
			      <label for="inputState">Fornecedor</label>
			      <input type="text" class="form-control" id="inputZip" required placeholder="Fornecedor" name="fornecedor" value="{{PRODUTO.pro_fornecedor}}">

			    </div>
			    <div class="form-group col-md-2">
			      <label for="inputZip">Preço</label>
			      <input type="decimal" class="form-control" id="inputZip" required placeholder="Preço" name="preco" value="{{PRODUTO.pro_preco}}">
			    </div>
			  </div>
				<div class="form-group">
			    	<label for="exampleFormControlTextarea1">Descrição do Produto </label>
			    	<input class="form-control" id="exampleFormControlTextarea1" name="descricao" value="{{PRODUTO.pro_descricao}}" rows="3"></input>
				</div>	
			  <input type="submit" value="Salvar" class="btn btn-primary">
			</form>
		</div>

		<div class="col-md-4">
		</div>
	</div>
</div>

<div class="container-fluid" style="display:flex; justify-content:center; align-items:center;">	
	<a href="{% url 'rmbebidas:defbtndellproduto' PRODUTO.pro_codigo %}">
	  <input type="submit" value="Excluir Produto" class="btn btn-danger">
	</a>
</div>

<div class="container-fluid" style="display: flex; align-items: center; justify-content: center;">
	{{getERROR2}}
</div>
{% endblock conteudo %}

</body>
</html>